server:
  port: 8081

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.112.149.206:3306/website?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#日志配置
logging:
  level:
    root: info
    com.roc: debug
  file:
    name: log/website.log